ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG VALIDATE_MODULES

COPY env/ /opt/python/
COPY wheels/ /offline/wheels/
COPY --chown=1000:1000 sdk/ /opt/mediacenter/
RUN chmod -R a+rX /opt/mediacenter

ENV PATH=/opt/python/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LD_LIBRARY_PATH=/opt/python/lib PYTHONPATH=/opt/mediacenter \
    PYTHONNOUSERSITE=1 PYTHONDONTWRITEBYTECODE=1 PIP_NO_INDEX=1 \
    HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 HF_DATASETS_OFFLINE=1 HOME=/tmp

RUN test -n "$VALIDATE_MODULES" \
    && /opt/python/bin/conda-unpack \
    && /opt/python/bin/python -m pip install --no-index --no-deps /offline/wheels/*.whl \
    && /opt/python/bin/python -m pip check \
    && /opt/python/bin/python -B -c \
       "import importlib,os,redis,ftfy,wcwidth; import mediacenter.video_worker_cli; [importlib.import_module(name) for name in os.environ['VALIDATE_MODULES'].split(',')]"

ENV VALIDATE_MODULES=${VALIDATE_MODULES}
USER 1000:1000
WORKDIR /opt/mediacenter
ENTRYPOINT ["/opt/python/bin/python","-B","-u","-m","mediacenter.video_worker_cli"]
